<?php
if ($this->isEnabled()) {
    $addToCartProducts = $this->getAddToCartProducts();
    $removeFromCartProduct = $this->getRemoveFromCartProduct();

    if (!$addToCartProducts && !$removeFromCartProduct) {
        // only fetch cart contents if no additions or removals
        $cartProductIds = $this->getCartProductIds();
    }

    if ($addToCartProducts || $removeFromCartProduct || !empty($cartProductIds)) {
?>
    <script type="text/javascript">
        _bluecoreTrack = window._bluecoreTrack || [];
        <?php if ($addToCartProducts) { ?>
            <?php foreach ($addToCartProducts as $productId) { ?>
                _bluecoreTrack.push(["trackAddToCart", <?php echo $this->getAddToCartEventData($productId) ?>, <?php echo $this->getEnvironment() ?>]);
            <?php } ?>
        <?php } elseif ($removeFromCartProduct) { ?>
            _bluecoreTrack.push(["trackRemoveFromCart", <?php echo $this->getRemoveFromCartEventData($removeFromCartProduct) ?>, <?php echo $this->getEnvironment() ?>]);
        <?php } elseif (!empty($cartProductIds)) { ?>
            _bluecoreTrack.push(["trackAddToCart", <?php echo $this->getViewCartEventData($cartProductIds) ?>, <?php echo $this->getEnvironment() ?>]);
        <?php } ?>
    </script>
<?php } ?>
<?php } ?>