<?php
/**
 * Test
 *
 * @var Bluecore_Integration_Block_Test $this
 */
?>


    <script type="text/javascript">
        var message = "TEST.phtml " + +(new Date());
        alert(message);
        console.warn(message);
    </script>








Spooky!

<!-- <img src="http://magento.local/media/catalog/product/cache/1/thumbnail/180x/9df78eab33525d08d6e5fb8d27136e95/a/c/ace001_1.jpg" alt="Jackie O Round Sunglasses" title="BIMMEL"> -->


<?php 
// echo $this->getChildHtml('bluecore_test')
 ?>